@startuml
skinparam rectangle {
    roundCorner<<Concept>> 25
}
rectangle "Apollo Auto" <<system>> as AA
rectangle "Open Vehicle Certification Platform" as OVCP
rectangle "Hardware Development Platform" as HDP
rectangle "Open Software Platform" as OSP
rectangle "Cloud Service Platform" as CSP
rectangle "Solutions" as S

AA --> OVCP
AA --> HDP
AA --> OSP
AA --> CSP
AA --> S
@enduml

@startuml
skinparam rectangle {
    roundCorner<<Concept>> 25
}
rectangle "Apollo Auto" <<system>> as AA {
component "IPC" as IPC
component "AXU" as AXU
component "ASU" as ASU
component "V2X OBU" as V2X
rectangle "Cyber RT" <<subsystem>> as C

component "Sensors" as SENS
}

C --> V2X
C -> IPC
C --> AXU
ASU -d-> SENS
C --> ASU: PCIe

@enduml


@startuml
skinparam rectangle {
    roundCorner<<Concept>> 25
}
rectangle "Apollo Auto" <<system>> as AA
rectangle "Sensors" as OVCP
rectangle "Hardware Development Platform" as HDP
rectangle "Open Software Platform" as OSP
rectangle "Cloud Service Platform" as CSP
rectangle "Solutions" as S

AA --> OVCP
AA --> HDP
AA --> OSP
AA --> CSP
AA --> S
@enduml