@startuml
Perception -> Prediction: Authentication Request
Prediction -> Planning: Authentication Response


Control -> Guardian: ControlCommand
CANBus -> Guardian: Chassis
System -> Guardian: SystemStatus

CANBus -> Control: Chassis
Localization -> Control: LocalizationEstimate
Planning -> Control: ADCTrajectory


Planning -> Routing: RoutingRequest
Routing --> Planning: RoutingResponse

Guardian -> CANBus

@enduml

@startuml
Perception -> Planning: TrafficLightDetection

Planning -> Routing: RoutingRequest
Routing --> Planning: RoutingResponse

Plannning -> ADCTrajectory

@enduml



@startuml
OnPlanning - [Control]
[Control] - OnPad
[Control] -- OnChassis
[Control] -- OnMonitor
[Control] -- OnLocalization

@enduml

@startuml
Vehicle -> CANBus: ChassisDetails
Control -> CANBus: ControlCommand 
Guardian -> CANBus: GuardianCommand
CANBus --> CyberRT: ChassisStatus
CANBus --> CyberRT: ChasisDetailsStatus 

@enduml