[[section-introduction-and-goals]]
==	Einführung und Ziele

:caution-caption: Der Link zum Repository lautet https://github.com/rocko/ost_sisidm_2021_apollo

Dieser Abschnitt führt in die Aufgabenstellung ein und skizziert die Ziele, die Apollo Auto verfolgt.

=== Aufgabenstellung

==== Was ist Apollo Auto?

Apollo ist eine hochleistungsfähige, flexible Architektur, die die Entwicklung, das Testen und den Einsatz von autonomen Fahrzeugen beschleunigt.
Apollo Auto bietet unter Andrem Lösungen für Valet Parking, V2X-Kommunikation und intelligente Lichtsignalanlagen.

==== Wesentliche Features:

* Valet Parking
** Software- und Hardware-Integrationslösung.
 Multifusionslösung bestand aus Fahrzeug, Cloud, HD-Karte und Parkplätzen
** Bietet hochwertige Dienstleistungen, wie automatische Parkplatzerkennung und autonomes Parken, für Kunden.

* V2X-Kommunikation
** Interaktionslösung für intelligente Fahrzeuginfrastruktur
** Apollo V2X umfasst ein intelligentes Transportsystem für Fahrzeug Straßendatenerfassung und intelligente Verarbeitungsanalyse, Verkehrssicherheit und -effizienz
** Wahrnehmung aller Verkehrsteilnehmer im Sichtfeld und die bereitgestellten straßenseitigen Sensorinformationen können für die Entscheidungsfindung beim autonomen Fahren auf hohem Niveau verwendet werden
** Wahrnehmung von Verkehrteilnehmern ausserhalb des Sichtfeldes

<<<

** Bietet einen vollständigen, kontinuierlichen, multimodalen Datendienst mit niedriger Latenz für L4-Autopilot-Fahrzeuge, die in mehreren Szenarien getestet wurden
** Durch die permanente dynamische Erfassung von Verkehrsinformationen und die Cloud-Integration, wird eine weltweite optimale kollaborative Steuerungsfunktionen für Verkehrsteilnehmer und Verkehrsmanagement erreicht

* Smart Traffic Signals
** Holographisches Wahrnehmen und Verstehen, basierend auf dem holografischen Wahrnehmungs- und Erkennungssystem
** Status von Fußgängern und Fahrzeugen auf jeder Fahrspur genau erkennen und die Leistung des aktuellen Verkehrsflusses wie Volumen, Warteschlangenlänge, Verspätungen usw.
** Vollständige raum-zeitliche Ableitung und Entscheidungsfindung
** Echtzeitsteuerung der gesamten Szene
** Reduzierung der durchschnittlichen Wartezeit um 20-30% während der Rush Hour

* Robotaxi
** Die Robotaxis, die aus Chinas erstem werkseitig installierten L4-Passagier-Fahrzeug sind zur Zeit auf öffentlichen Straßen im Testbetrieb
** Sie werden in Kooperation von Baido und FAW an einer gemeinsamen Produktionsline hergstellt

* Minibus
** Die Minibusse ermöglichen ebenfalls autonomes Fahren der Stufe 4
** Funktionen sind unter Anderem Hinderniserkennung und -vermeidung, zu einem Zielort Fahren und Kreuzungen überqueren

<<<


=== Qualitätsziele

Die folgende Tabelle beschreibt die zentralen Qualitätsziele von DokChess, wobei die Reihenfolge eine grobe Orientierung bezüglich der Wichtigkeit vorgibt.

[cols="1,2" options="header"]
|===
|Qualitätsziel |Motivation und Erläuterung
| _Zugängliches Beispiel (Analysierbarkeit)_ |
[small]#Apollo Auto ist eine offene Plattform, daher ist es wichtig, dass sich neue Entwickler möglichst schnell in die Architektur, Entwurf und Implementierung einarbeiten können.#
| _Schnelle Reaktion auf Fahrsituationen (Zeitverhalten)_ |
[small]#Apollo Auto übernimmt zuverlässig und sicher die autonome Steuerung von Fahrzeugen.#
//| _Echtzeit Umfelderkennung (Zeitverhalten)_  |
//[small]#Für die Steuerung von Fahrzeugen wird ein Modell des Umfelds benötigt.
//Aus den Sensoprdaten wird ein digitales Abbild des Fahrweges, von beweglichen und unbeweglichen Hindernissen und von Signalen geschaffen#

| _Interoperabilität_ |
[small]#Um die Fahrsicherheit weiter zu erhöhen, werden große Mengen an Sensor- und Zustandsdaten gesammelt, mit denen das Fahrzeug schnell auf Veränderungen reagieren kann.#
|===

<<<

=== Stakeholder

Die folgende Tabelle stellt die Stakeholder von Apollo Auto und ihre jeweilige Intention dar.

[cols="1,2" options="header"]
|===
|Rolle |Interesse, Bezug
| _Softwarearchitekten_ |
[small]#Wollen ein Gefühl bekommen, wie Architekturdokumentation für ein konkretes System aussehen kann.
Möchten sich Dinge (z.B. Form, Notation) für Ihre tägliche Arbeit abgucken.
Gewinnen Sicherheit für Ihre eigenen Projekte.#
| _Entwickler_ |
[small]#Nehmen Architekturaufgaben im Team wahr.
Brauchen ein generelles Verständnis für die Architektur.#
| _OEM & Lieferanten_ |
[small]#Entwickeln neue Produkte auf Grundlage von Apollo Auto.
Wollen Anregungen für eigene Produkte finden.#

| _Gesetzgeber & Genehmigungsbehörden_ |
[small]#Entwickeln einen gesetzlichen Rahmen zur Zulassung von fahrerlosen Fahrzeugen im öffentlichen Straßenverkehr.
Etablieren Prüfvorschriften und Tests für Genehmigungsverfahren.#
| _Universitäten_ |
[small]#Entwickeln eigene Forschungsprojekte auf Grundlage von Apollo Auto.
Wollen Anregungen für weitere Forschungsprojekte und studentische Arbeiten finden.#
| _Studenten_ |
[small]#Interessieren sich aufgrund ihres Studiums für die verschiedenen Aspekte einer Architekturdokumentation.
Setzen eigene Projekte (z.B. Masterarbeit) zum Thema autonomes Fahren mit Apollo Auto um.
Schreiben eine Architekturdokumentation zu Apollo Auto.#
|===


// DONE