[[section-introduction-and-goals]]
==	Einführung und Ziele

Dieser Abschnitt führt in die Aufgabenstellung ein und skizziert die Ziele, die Apollo Auto verfolgt.


=== Aufgabenstellung

==== Was ist Apollo Auto?
Apollo ist eine hochleistungsfähige, flexible Architektur, die die Entwicklung, das Testen und den Einsatz von autonomen Fahrzeugen beschleunigt.
Apollo Auto bietet unter Andrem Lösungen für Valet Parking, V2X-Kommunikation und intelligente Lichtsignalanlagen.

==== Wesentliche Features:

* Valet Parking
** Software- und Hardware-Integrationslösung.
 Multifusionslösung bestand aus Fahrzeug, Cloud, HD-Karte und Parkplätzen
** Bietet hochwertige Dienstleistungen, wie automatische Parkplatzerkennung und autonomes Parken, für Kunden.


* V2X-Communication
** Interaktionslösung für intelligente Fahrzeuginfrastruktur
** Apollo V2X umfasst ein intelligentes Transportsystem für Fahrzeug Straßendatenerfassung und intelligente Verarbeitungsanalyse, Verkehrssicherheit und -effizienz
** Wahrnehmung aller Verkehrsteilnehmer im Sichtfeld und die bereitgestellten straßenseitigen Sensorinformationen können für die Entscheidungsfindung beim autonomen Fahren auf hohem Niveau verwendet werden
** Wahrnehmung von Verkehrteilnehmern ausserhalb des Sichtfeldes
** Bietet einen vollständigen, kontinuierlichen, multimodalen Datendienst mit niedriger Latenz für L4-Autopilot-Fahrzeuge, die in mehreren Szenarien getestet wurden
** Durch die permanente dynamische Erfassung von Verkehrsinformationen und die Cloud-Integration, wird eine weltweite optimale kollaborative Steuerungsfunktionen für Verkehrsteilnehmer und Verkehrsmanagement erreicht

* Smart Traffic Signals
** Holographisches Wahrnehmen und Verstehen, basierend auf dem holografischen Wahrnehmungs- und Erkennungssystem
** Status von Fußgängern und Fahrzeugen auf jeder Fahrspur genau erkennen und die Leistung des aktuellen Verkehrsflusses wie Volumen, Warteschlangenlänge, Verspätungen usw.
** Vollständige raum-zeitliche Ableitung und Entscheidungsfindung
** Echtzeitsteuerung der gesamten Szene
** Reduzierung der durchschnittlichen Wartezeit um 20-30% während der Rush Hour

* Robotaxi
** Die Robotaxis, die aus Chinas erstem werkseitig installierten L4-Passagier-Fahrzeug sind zur Zeit auf öffentlichen Straßen im Testbetrieb
** Sie werden in Kooperation von Baido und FAW an einer gemeinsamen Produktionsline hergstellt

* Minibus
** Die Minibusse ermöglichen ebenfalls autonomes Fahren der Stufe 4
** Funktionen sind unter Anderem Hinderniserkennung und -vermeidung, zu einem Zielort Fahren und Kreuzungen überqueren

=== Qualitätsziele
Die folgende Tabelle beschreibt die zentralen Qualitätsziele von DokChess, wobei die Reihenfolge eine grobe Orientierung bezüglich der Wichtigkeit vorgibt.
[cols="1,2" options="header"]
|===
|Qualitätsziel |Motivation und Erläuterung
| _<Rolle-1>_ | _<Kontakt-1>_ _
| _<Rolle-2>_ | _<Kontakt-2>_ _
| _<Rolle-2>_ | _<Kontakt-2>_ _
| _<Rolle-2>_ | _<Kontakt-2>_ _
| _<Rolle-2>_ | _<Kontakt-2>_ _
|===

=== Stakeholder



Die folgende Tabelle stellt die Stakeholder von Apollo Auto und ihre jeweilige Intention dar.
[cols="1,2" options="header"]
|===
|Rolle |Interesse, Bezug
| _Softwarearchitekten_ | _<Erwartung-1>
| _Entwickler_ | _<Kontakt-2>_
| _OEM & Lieferanten_ | _<Kontakt-2>_
| _Gesetzgeber & Genehmigungsbehörden_ | _<Kontakt-2>_
| _Universitäten_ | _<Kontakt-2>_
| _Studenten_ | _<Kontakt-2>_
|===
