[[section-architecture-constraints]]
== Randbedingungen

Beim Einsatz von Apollo sind verschiedene Randbedingungen zu beachten.
Dieser Abschnitt stellt sie dar und erklärt auch – wo nötig – deren Motivation.


=== Technische Randbedingungen
* Ein Fahrzeug, das mit dem By-Wire-System ausgestattet ist, einschließlich, aber nicht beschränkt auf Brake-by-Wire, Steering-by-Wire, Throttle-by-Wire und Shift-by-Wire (Apollo wird derzeit auf Lincoln MKZ getestet).

* Ein Rechner mit einem 4-Kern-Prozessor und mindestens 8 GB Speicher (16 GB für Apollo 3.5 und höher)

* Ubuntu 18.04

* Arbeitskenntnisse über Docker

=== Organisatorische Randbedingungen
[cols="e,2e" options="header"]

hier irgendwas das github verwendet wird ....
sonst kein plan wie die arbeiten, denke mal auch verteilt

|===
|Randbedingung | Erläuterungen, Hintergrund
|github
|Quellcode ist über github verfügbar.
|===

=== Konventionen
[cols="e,2e" options="header"]
|===
|Konvention | Erläuterungen, Hintergrund
|Dokumentation
|Terminologie und Gliederung nach dem deutschen arc42-Template in der Version 6.0
|Kodierrichtlinien für C++
|C++ Coding Conventions von Sun/Oracle, geprüft mit Hilfe von CheckStyle
|Kodierrichtlinien für Python
|Python Coding Conventions von Sun/Oracle, geprüft mit Hilfe von CheckStyle
|===
