[[section-technical-risks]]
== Risiken

Die folgenden Risiken wurden zu Beginn des Vorhabens identifiziert. Sie beeinflussten die Planung der ersten drei Iterationen maßgeblich. Seit Abschluss der dritten Iteration werden sie beherrscht. Dieser Architekturüberblick zeigt die Risiken inklusive der damaligen Eventualfallplanung weiterhin, wegen ihres großen Einflusses auf die Lösung.

//[role="arc42help"]
//****
//.Inhalt
//Eine nach Prioritäten geordnete Liste der erkannten Architekturrisiken und/oder technischen Schulden.

//.Motivation
//"Risikomanagement ist Projektmanagement für Erwachsene."
//-- Tim Lister, Atlantic Systems Guild

//Unter diesem Motto sollten Sie Architekturrisiken und/oder technische Schulden gezielt ermitteln, bewerten und Ihren Management-Stakeholdern (z.B. Projektleitung, Product-Owner) transparent machen.

//.Form
//Liste oder Tabelle von Risiken und/oder technischen Schulden, eventuell mit vorgeschlagenen Maßnahmen zur Risikovermeidung, Risikominimierung oder dem Abbau der technischen Schulden.
//****

=== Angriffe von Außen
Da Moderne autonome Fahrzeuge über By-Wire Systeme verfügen und zukünftig keine mechanischen Eingriffmöglichkeiten mehr bieten werden, sind Sie besonders anfällig für Hackerangriffe, zum Beispiel zum Tötungszweck.

Folgend einige Beispiele für mögliche Angriffe auf Autonome Fahrzeuge:

* Hacking
** Eingriffe über Hardware Schnittstellen
** Entfernte Angriffe über die Cloudanbindung

* Beeinträchtigung des GNSS (global navigation satellite system)
** Jamming
** Spoofing

* Visuelle Eingriffe
** Manipulation von Lichtsignalanlagen
** Veränderung von Verkehrszeichen
** Veränderung von Leitlinien oder Fahrbahnbegrenzungen

* Eingriffe in die Datenübertragung
** Signalabschirmung
** Fälschung von Verkehrsdaten über V2X oder Internet

<<<

Hacking:
Sowohl über Hardware Schnittstellen zur Diagnose und Wartung, als auch über die Schnittstelle zum Internet, für Over-the-Air-Updates und Datenaustausch), kann Schadsoftware in das Netzwerk gelangen.
Dabei kann es sich zum Einen um Spyware zum Ausspähen vertraulicher z.B. personenbezogener Daten, wie zum Beispiel den genauen Standort handeln.
Zum Anderen kann Maleware benutzt werden, um das Fahrzeug funktionsunfähig zu machen, oder einen mitunter tödlichen Unfall zu verursachen.

Beeinträchtigung GNSS:
Die Positionsbestimmung mit GNSS basiert auf dem Empfang von Positionsdaten über Elektromagnetische Wellen.
Dieser Übertragungsweg eröffnet einige mögliche Angriffswege, wie Jamming und Spoofing.
Beim Jamming wird das GNSS-Signal mittels Interferenz(Überlagerung der Signalwellen) gestört. Damit kann das Fahrzeug seine aktuelle Position nicht mehr bestimmen.
Bei einem Spoofing-Angriff werden dem Fahrzeug gefälschte Positionsdaten gesendet. Damit kann das Fahrzeug fehlgeleitet werden.

Visuelle Eingriffe:
Die Steuerung von autonomen Fahrzeugen beruht zum größten Teil auf Sensordaten. Diese können gezielt visuell manipuliert werden.
Zum Beispiel ist es möglich Lichtanlagen zu manipulieren, um Fahrzeuge an Kreuzungen in den kreuzenden Verkehr fahren zu lassen.
Außerdem können Verkehrszeichen abgeändert werden, um zum Beispiel Geschwindigkeiten stark zu überhöhen (z.B. 130km/h anstatt 30km/h).
Fahrtrajektorien werden unter Anderem aufgrund der Fahrbahnbegrenzung ermittelt. Diese kann sehr einfach mechanisch manipuliert werden.
Test haben ergeben, dass generell, aber im Besonderen auch im Bereich von Baustellen die Fahrspurerkennung Fehler- und Manipulationsanfällig ist.

Eingriffe in die Datenübertragung:
Wie beim GNSS können generell Störsender benutzt werden, um die Datenübertragung zum autonomen Fahrzeug zu unterbrechen.
Dann fährt das Fahrzeug ohne externe Verkehrsinformationen und kann ausschließlich auf der Grundlage der eigenen Sensorinformationen navigieren.
Außerdem können auch hier wieder Fehlinformationen gesendet werden, um zum Beispiel unnötige riskante Ausweichmanöver auszulösen.

Um zu verhindern, dass in Fahrzeuge mit Apollo Auto von außen eingegriffen wird, bietet Apollo Auto einige Sicherheitsfunktionen.

Cyber Security Produkte:

* Secure IVI:

Ein Produkt, das das IVI-System sichert. Es kann die Legitimität von Anwendungen überwachen, unbefugte Softwareinstallationen verhindern und verdächtige Verbindungen und Portzugriffe filtern.
Es schützt auch die Privatsphäre der Benutzer und das IVI-Urheberrecht.

* IDPS（Intrusion Detection and Prevention System）

Ein Sicherheitsprodukt zur Identifizierung anormaler Daten und Verhaltensweisen im Fahrzeug, um zu verhindern, dass sie sich auf das gesamte Fahrzeugnetzwerk ausbreiten.
Durch die Kombination mehrerer Erkennungs-Engines kann es die Anomalie im Fahrzeug vollständig erkennen.

* CANScan

Ein Produkt für den Sicherheitstest von CAN und Steuergeräten.
Mit einer umfangreichen Testfallbibliothek kann es Sicherheitstestanalysen auf verschiedenen Steuergeräten durchführen und Schwachstellen schnell ausfindig machen.


Zusammenfassend kann festgehalten werden, dass die Sicherheitsrisiken bei autonomen Fahrzeugen enorm sind.
Apollo Auto bietet erste Funktionen die für eine erhöhte Cybersecurity sorgen.
Besonders gegen komplexe Angriffe mit mehreren kombinierten Verfahren müssen die Sicherheitslösungen aber noch weiterentwickelt werden.